base:
  seed: 719
  fold_num: 5
  epochs: 10
  optuna: False
  train_bs: 8
  valid_bs: 16
  accum_iter: 2

dataset:
  class: BrainTumor2dSimpleDataset
  img_size: none

model:
  class: BrainTumor2dModel
  model_arch: efficientnet-b0
  pretrained: True

optimizer:
  type: Adam
  lr: 1e-3
  weight_decay: 0.0

scheduler:
  type: ReduceLROnPlateau
  mode: min
  patience: 3
  min_lr: 1e-6

