experiment_name: Simple Baseline
bucket_name: brain-tumor-mlflow
csv_file: train_labels.csv

base:
  seed: 719
  fold_num: 5
  epochs: 10
  optuna: false
  train_bs: 8
  valid_bs: 16
  num_workers: 4
  accum_iter: 2

dataset:
  class: BrainTumor2dSimpleDataset
  img_size: 256

model:
  class: BrainTumor2dModel
  model_arch: efficientnet_b0
  pretrained: true

optimizer:
  name: Adam
  lr: 1.0e-3
  weight_decay: 0.0

scheduler:
  name: ReduceLROnPlateau
  mode: min
  patience: 3
  min_lr: 1.0e-6

